# # This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Feature/Bugfix branch

on:
#   workflow_call:
  push:
    branches:
      - feature-*
      - bugfix-*
      - dev
      - test
  pull_request:
    branches:
        - feature-*
        - bugfix-*
        - dev
        - test
    paths:
      - package.json
      - CHANGELOG 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v2

    - name: Setting up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.16.0'

    - name: Installing dependencies 
      run: npm ci
      
    - name: Run tests
      run: |
        npm run test
        npx jest --coverage | tee ./coverage.txt && exit ${PIPESTATUS[0]}

    - name: Jest Coverage Comment
      uses: MishaKav/jest-coverage-comment@main
      with:
        coverage-path: ./coverage.txt
        
